let gridX = 18;
let gridY = 10;

let blobWidth = 20;
let blobHeight = 20;

let regions = [

  // NORTHERN IRELAND

  { name: "Belfast East", areas: [{ coordinates: [[4, 33]] }] },
  { name: "Belfast North", areas: [{ coordinates: [[3, 32]] }] },
  { name: "Belfast South", areas: [{ coordinates: [[3, 34]] }] },
  { name: "Belfast West", areas: [{ coordinates: [[2, 33]] }] },
  { name: "East Antrim", areas: [{ coordinates: [[4, 29]] }] },
  { name: "East Londonderry", areas: [{ coordinates: [[2, 27]] }] },
  { name: "Fermanagh & South Tyrone", areas: [{ coordinates: [[0, 31]] }] },
  { name: "Foyle", areas: [{ coordinates: [[1, 28]] }] },
  { name: "Lagan Valley", areas: [{ coordinates: [[2, 31]] }] },
  { name: "Mid Ulster", areas: [{ coordinates: [[2, 29]] }] },
  { name: "Newry & Armagh", areas: [{ coordinates: [[1, 34]] }] },
  { name: "North Antrim", areas: [{ coordinates: [[3, 28]] }] },
  { name: "North Down", areas: [{ coordinates: [[4, 35]] }] },
  { name: "South Antrim", areas: [{ coordinates: [[3, 30]] }] },
  { name: "South Down", areas: [{ coordinates: [[2, 35]] }] },
  { name: "Strangford", areas: [{ coordinates: [[3, 36]] }] },
  { name: "Upper Bann", areas: [{ coordinates: [[1, 30]] }] },
  { name: "West Tyrone", areas: [{ coordinates: [[0, 29]] }] },

  // SCOTLAND

  { name: "Aberdeen North", areas: [{ coordinates: [[15, 4]] }] },
  { name: "Aberdeen South", areas: [{ coordinates: [[16, 5]] }] },
  { name: "Aberdeenshire West & Kincardine", areas: [{ coordinates: [[15, 8]] }] },
  { name: "Airdrie & Shotts", areas: [{ coordinates: [[13, 12]] }] },
  { name: "Angus", areas: [{ coordinates: [[16, 9]] }] },
  { name: "Argyll & Bute", areas: [{ coordinates: [[10, 11]] }] },
  { name: "Ayr, Carrick & Cumnock", areas: [{ coordinates: [[10, 17]] }] },
  { name: "Ayrshire Central", areas: [{ coordinates: [[10, 15]] }] },
  { name: "Ayrshire North & Arran", areas: [{ coordinates: [[9, 14]] }] },
  { name: "Banuff & Buchan", areas: [{ coordinates: [[14, 3]] }] },
  { name: "Berwickshire, Roxburgh & Selkirk", areas: [{ coordinates: [[15, 20]] }] },
  { name: "Caithness, Sutherland & Easter Ross", areas: [{ coordinates: [[12, 1]] }] },
  { name: "Coatbridge, Chryston & Bellshill", areas: [{ coordinates: [[12, 15]] }] },
  { name: "Cumbernauld, Kilsyth & Kirkintilloch East", areas: [{ coordinates: [[11, 8]] }] },
  { name: "Dumfries & Galloway", areas: [{ coordinates: [[12, 21]] }] },
  { name: "Dumfriesshire, Clydesdale & Tweedale", areas: [{ coordinates: [[11, 20]] }] },
  { name: "Dunbartonshire East", areas: [{ coordinates: [[12, 13]] }] },
  { name: "Dunbartonshire West", areas: [{ coordinates: [[11, 6]] }] },
  { name: "Dundee East", areas: [{ coordinates: [[14, 7]] }] },
  { name: "Dundee West", areas: [{ coordinates: [[13, 6]] }] },
  { name: "Dunfermline & West Fife", areas: [{ coordinates: [[13, 8]] }] },
  { name: "East Kilbridge, Strathaven & Lesmahagow", areas: [{ coordinates: [[13, 18]] }] },
  { name: "East Lothian", areas: [{ coordinates: [[14, 11]] }] },
  { name: "Edinburgh East", areas: [{ coordinates: [[16, 15]] }] },
  { name: "Edinburgh North & Leith", areas: [{ coordinates: [[15, 14]] }] },
  { name: "Edinburgh South West", areas: [{ coordinates: [[14, 17]] }] },
  { name: "Edinburgh South", areas: [{ coordinates: [[15, 16]] }] },
  { name: "Edinburgh West", areas: [{ coordinates: [[14, 15]] }] },
  { name: "Falkirk", areas: [{ coordinates: [[12, 7]] }] },
  { name: "Fife North East", areas: [{ coordinates: [[14, 9]] }] },
  { name: "Glasgow Central", areas: [{ coordinates: [[12, 11]] }] },
  { name: "Glasgow East", areas: [{ coordinates: [[12, 17]] }] },
  { name: "Glasgow North East", areas: [{ coordinates: [[13, 14]] }] },
  { name: "Glasgow North West", areas: [{ coordinates: [[11, 10]] }] },
  { name: "Glasgow North", areas: [{ coordinates: [[12, 9]] }] },
  { name: "Glasgow South West", areas: [{ coordinates: [[11, 14]] }] },
  { name: "Glasgow South", areas: [{ coordinates: [[11, 16]] }] },
  { name: "Glenrothes", areas: [{ coordinates: [[15, 10]] }] },
  { name: "Gordon", areas: [{ coordinates: [[15, 6]] }] },
  { name: "Inverclyde", areas: [{ coordinates: [[10, 13]] }] },
  { name: "Inverness, Nairn, Badenoch & Strathspey", areas: [{ coordinates: [[10, 9]] }] },
  { name: "Kilmarnock & Loudoun", areas: [{ coordinates: [[13, 20]] }] },
  { name: "Kirkcaldy & Cowdenbeath", areas: [{ coordinates: [[14, 13]] }] },
  { name: "Lanark & Hamilton East", areas: [{ coordinates: [[14, 21]] }] },
  { name: "Linlithgow & Falkirk East", areas: [{ coordinates: [[13, 10]] }] },
  { name: "Livingston", areas: [{ coordinates: [[14, 19]] }] },
  { name: "Midlothian", areas: [{ coordinates: [[15, 18]] }] },
  { name: "Moray", areas: [{ coordinates: [[14, 5]] }] },
  { name: "Motherwell & Wishaw", areas: [{ coordinates: [[13, 16]] }] },
  { name: "Na H-Eileanan An Iar [Western Isles]", areas: [{ coordinates: [[9, 4]] }] },
  { name: "Ochil & South Perthshire", areas: [{ coordinates: [[13, 4]] }] },
  { name: "Orkney & Shetland", areas: [{ coordinates: [[15, 0]] }] },
  { name: "Paisley & Renfrewshire North", areas: [{ coordinates: [[11, 12]] }] },
  { name: "Paisley & Renfrewshire South", areas: [{ coordinates: [[10, 19]] }] },
  { name: "Perth & Perthshire North", areas: [{ coordinates: [[12, 3]] }] },
  { name: "Renfrewshire East", areas: [{ coordinates: [[11, 18]] }] },
  { name: "Ross, Skye & Lochaber", areas: [{ coordinates: [[10, 7]] }] },
  { name: "Rutherglen & Hamilton West", areas: [{ coordinates: [[12, 19]] }] },
  { name: "Stirling", areas: [{ coordinates: [[12, 5]] }] },

  // ENGLAND

  { name: "Newcastle Upon Tyne North", areas: [{ coordinates: [[16, 19]] }] },
  { name: "Berwick-Upon-Tweed", areas: [{ coordinates: [[17, 18]] }] },
  { name: "Workington", areas: [{ coordinates: [[14, 23]] }] },
  { name: "Carlisle", areas: [{ coordinates: [[15, 22]] }] },
  { name: "Blaydon", areas: [{ coordinates: [[16, 21]] }] },
  { name: "Tyneside North", areas: [{ coordinates: [[17, 20]] }] },
  { name: "Wansbeck", areas: [{ coordinates: [[18, 19]] }] },
  { name: "Blyth Valley", areas: [{ coordinates: [[19, 18]] }] },
  { name: "Barrow & Furness", areas: [{ coordinates: [[14, 25]] }] },
  { name: "Copeland", areas: [{ coordinates: [[15, 24]] }] },
  { name: "Hexham", areas: [{ coordinates: [[16, 23]] }] },
  { name: "Newcastle Upon Tyne Central", areas: [{ coordinates: [[17, 22]] }] },
  { name: "Gateshead", areas: [{ coordinates: [[18, 21]] }] },
  { name: "Newcastle Upon Tyne East", areas: [{ coordinates: [[19, 20]] }] },
  { name: "Tynemouth", areas: [{ coordinates: [[20, 19]] }] },
  { name: "Wyre & Preston North", areas: [{ coordinates: [[12, 29]] }] },
  { name: "Preston", areas: [{ coordinates: [[13, 28]] }] },
  { name: "Lancaster & Fleetwood", areas: [{ coordinates: [[14, 27]] }] },
  { name: "Westmorland & Lonsdale", areas: [{ coordinates: [[15, 26]] }] },
  { name: "Penrith & The Border", areas: [{ coordinates: [[16, 25]] }] },
  { name: "Durham North West", areas: [{ coordinates: [[17, 24]] }] },
  { name: "Durham North", areas: [{ coordinates: [[18, 23]] }] },
  { name: "Washington & Sunderland West", areas: [{ coordinates: [[19, 22]] }] },
  { name: "Jarrow", areas: [{ coordinates: [[20, 21]] }] },
  { name: "South Shields", areas: [{ coordinates: [[21, 20]] }] },
  { name: "Blackpool North & Cleveleys", areas: [{ coordinates: [[12, 31]] }] },
  { name: "Flyde", areas: [{ coordinates: [[13, 30]] }] },
  { name: "Blackburn", areas: [{ coordinates: [[14, 29]] }] },
  { name: "Ribble Valley", areas: [{ coordinates: [[15, 28]] }] },
  { name: "Morcambe & Lunesdale", areas: [{ coordinates: [[16, 27]] }] },
  { name: "Bishop Auckland", areas: [{ coordinates: [[17, 26]] }] },
  { name: "Sedgefield", areas: [{ coordinates: [[18, 25]] }] },
  { name: "Durham, City of", areas: [{ coordinates: [[19, 24]] }] },
  { name: "Houghton & Sunderland South", areas: [{ coordinates: [[20, 23]] }] },
  { name: "Sunderland Central", areas: [{ coordinates: [[21, 22]] }] },
  { name: "Lancashire West", areas: [{ coordinates: [[10, 35]] }] },
  { name: "South Ribble", areas: [{ coordinates: [[11, 34]] }] },
  { name: "Blackpool South", areas: [{ coordinates: [[12, 33]] }] },
  { name: "Bury North", areas: [{ coordinates: [[13, 32]] }] },
  { name: "Rossendale & Darwen", areas: [{ coordinates: [[14, 31]] }] },
  { name: "Hyndburn", areas: [{ coordinates: [[15, 30]] }] },
  { name: "Pendle", areas: [{ coordinates: [[16, 29]] }] },
  { name: "Darlington", areas: [{ coordinates: [[17, 28]] }] },
  { name: "Stockton South", areas: [{ coordinates: [[18, 27]] }] },
  { name: "Stockton North", areas: [{ coordinates: [[19, 26]] }] },
  { name: "Middlesbrough", areas: [{ coordinates: [[20, 25]] }] },
  { name: "Easington", areas: [{ coordinates: [[21, 24]] }] },
  { name: "Hartlepool", areas: [{ coordinates: [[22, 23]] }] },
  { name: "Southport", areas: [{ coordinates: [[10, 37]] }] },
  { name: "Wigan", areas: [{ coordinates: [[11, 36]] }] },
  { name: "Chorley", areas: [{ coordinates: [[12, 35]] }] },
  { name: "Bolton North East", areas: [{ coordinates: [[13, 34]] }] },
  { name: "Heywood & Middleton", areas: [{ coordinates: [[14, 33]] }] },
  { name: "Rochdale", areas: [{ coordinates: [[15, 32]] }] },
  { name: "Burnley", areas: [{ coordinates: [[16, 31]] }] },
  { name: "Keighley", areas: [{ coordinates: [[17, 30]] }] },
  { name: "Pudsey", areas: [{ coordinates: [[18, 29]] }] },
  { name: "Harrogate & Knaresborough", areas: [{ coordinates: [[19, 28]] }] },
  { name: "Skipton & Ripon", areas: [{ coordinates: [[20, 27]] }] },
  { name: "Richmond [Yorks]", areas: [{ coordinates: [[21, 26]] }] },
  { name: "Redcar", areas: [{ coordinates: [[22, 25]] }] },
  { name: "Middlesbrough South & Cleveland East", areas: [{ coordinates: [[23, 24]] }] },
  { name: "Bootle", areas: [{ coordinates: [[9, 40]] }] },
  { name: "Sefton Central", areas: [{ coordinates: [[10, 39]] }] },
  { name: "Liverpool Walton", areas: [{ coordinates: [[11, 38]] }] },
  { name: "Bolton West", areas: [{ coordinates: [[12, 37]] }] },
  { name: "Bolton South East", areas: [{ coordinates: [[13, 36]] }] },
  { name: "Oldham West & Royton", areas: [{ coordinates: [[14, 35]] }] },
  { name: "Oldham East & Saddleworth", areas: [{ coordinates: [[15, 34]] }] },
  { name: "Colne Valley", areas: [{ coordinates: [[16, 33]] }] },
  { name: "Calder Valley", areas: [{ coordinates: [[17, 32]] }] },
  { name: "Shipley", areas: [{ coordinates: [[18, 31]] }] },
  { name: "Leeds North West", areas: [{ coordinates: [[19, 30]] }] },
  { name: "Leeds West", areas: [{ coordinates: [[20, 29]] }] },
  { name: "Selby & Ainsty", areas: [{ coordinates: [[21, 28]] }] },
  { name: "Thirsk & Malton", areas: [{ coordinates: [[22, 27]] }] },
  { name: "Scarborough & Whitby", areas: [{ coordinates: [[23, 26]] }] },
  { name: "Wirral West", areas: [{ coordinates: [[9, 42]] }] },
  { name: "Wallasey", areas: [{ coordinates: [[10, 41]] }] },
  { name: "Liverpool West Derby", areas: [{ coordinates: [[11, 40]] }] },
  { name: "Knowsley", areas: [{ coordinates: [[12, 39]] }] },
  { name: "Blackley & Broughton", areas: [{ coordinates: [[13, 38]] }] },
  { name: "Bury South", areas: [{ coordinates: [[14, 37]] }] },
  { name: "Ashton-under-Lyne", areas: [{ coordinates: [[15, 36]] }] },
  { name: "Sheffield Hallam", areas: [{ coordinates: [[16, 35]] }] },
  { name: "Bradford West", areas: [{ coordinates: [[17, 34]] }] },
  { name: "Bradford East", areas: [{ coordinates: [[18, 33]] }] },
  { name: "Leeds North East", areas: [{ coordinates: [[19, 32]] }] },
  { name: "Elmet & Rothwell", areas: [{ coordinates: [[20, 31]] }] },
  { name: "Leeds East", areas: [{ coordinates: [[21, 30]] }] },
  { name: "York Central", areas: [{ coordinates: [[22, 29]] }] },
  { name: "York Outer", areas: [{ coordinates: [[23, 28]] }] },
  { name: "Birkenhead", areas: [{ coordinates: [[9, 44]] }] },
  { name: "Liverpool Riverside", areas: [{ coordinates: [[10, 43]] }] },
  { name: "Liverpool Wavertree", areas: [{ coordinates: [[11, 42]] }] },
  { name: "St Helens North", areas: [{ coordinates: [[12, 41]] }] },
  { name: "Makerfield", areas: [{ coordinates: [[13, 40]] }] },
  { name: "Manchester Central", areas: [{ coordinates: [[14, 39]] }] },
  { name: "Stalybridge & Hyde", areas: [{ coordinates: [[15, 38]] }] },
  { name: "Stoke-on-Trent North", areas: [{ coordinates: [[16, 37]] }] },
  { name: "Sheffield Central", areas: [{ coordinates: [[17, 36]] }] },
  { name: "Halifax", areas: [{ coordinates: [[18, 35]] }] },
  { name: "Wakefield", areas: [{ coordinates: [[19, 34]] }] },
  { name: "Bradford South", areas: [{ coordinates: [[20, 33]] }] },
  { name: "Batley & Spen", areas: [{ coordinates: [[21, 32]] }] },
  { name: "Morley & Outwood", areas: [{ coordinates: [[22, 31]] }] },
  { name: "Leeds Central", areas: [{ coordinates: [[23, 30]] }] },
  { name: "Yorkshire East", areas: [{ coordinates: [[24, 29]] }] },
  { name: "Wirral South", areas: [{ coordinates: [[10, 45]] }] },
  { name: "Halton", areas: [{ coordinates: [[11, 44]] }] },
  { name: "St Helens South & Whiston", areas: [{ coordinates: [[12, 43]] }] },
  { name: "Leigh", areas: [{ coordinates: [[13, 42]] }] },
  { name: "Denton & Reddish", areas: [{ coordinates: [[14, 41]] }] },
  { name: "Shropshire North", areas: [{ coordinates: [[15, 40]] }] },
  { name: "Newcastle-under-Lyme", areas: [{ coordinates: [[16, 39]] }] },
  { name: "Stoke-on-Trent Central", areas: [{ coordinates: [[17, 38]] }] },
  { name: "Sheffield Heeley", areas: [{ coordinates: [[18, 37]] }] },
  { name: "Huddersfield", areas: [{ coordinates: [[19, 36]] }] },
  { name: "Barnsley East", areas: [{ coordinates: [[20, 35]] }] },
  { name: "Barnsley Central", areas: [{ coordinates: [[21, 34]] }] },
  { name: "Hemsworth", areas: [{ coordinates: [[22, 33]] }] },
  { name: "Normanton, Pontefract & Castleford", areas: [{ coordinates: [[23, 32]] }] },
  { name: "Beverley & Holderness", areas: [{ coordinates: [[24, 31]] }] },
  { name: "Ellesmere Port & Neston", areas: [{ coordinates: [[10, 47]] }] },
  { name: "Garston & Halewood", areas: [{ coordinates: [[11, 46]] }] },
  { name: "Warrington South", areas: [{ coordinates: [[12, 45]] }] },
  { name: "Worsley & Eccles South", areas: [{ coordinates: [[13, 44]] }] },
  { name: "Hazel Grove", areas: [{ coordinates: [[14, 43]] }] },
  { name: "Shrewsbury & Atcham", areas: [{ coordinates: [[15, 42]] }] },
  { name: "Telford", areas: [{ coordinates: [[16, 41]] }] },
  { name: "Wrekin, The", areas: [{ coordinates: [[17, 40]] }] },
  { name: "Stoke-on-Trent South", areas: [{ coordinates: [[18, 39]] }] },
  { name: "Sheffield South East", areas: [{ coordinates: [[19, 38]] }] },
  { name: "Dewsbury", areas: [{ coordinates: [[20, 37]] }] },
  { name: "Penistone & Stocksbridge", areas: [{ coordinates: [[21, 36]] }] },
  { name: "Sheffield Brightside & Hillsborough", areas: [{ coordinates: [[22, 35]] }] },
  { name: "Rotherham", areas: [{ coordinates: [[23, 34]] }] },
  { name: "Wentworth & Dearne", areas: [{ coordinates: [[24, 33]] }] },
  { name: "Hull East", areas: [{ coordinates: [[25, 32]] }] },
  { name: "Chester, City of", areas: [{ coordinates: [[11, 48]] }] },
  { name: "Weaver Vale", areas: [{ coordinates: [[12, 47]] }] },
  { name: "Warrington North", areas: [{ coordinates: [[13, 46]] }] },
  { name: "Stretford & Urmston", areas: [{ coordinates: [[14, 45]] }] },
  { name: "Salford & Eccles", areas: [{ coordinates: [[15, 44]] }] },
  { name: "Ludlow", areas: [{ coordinates: [[16, 43]] }] },
  { name: "Cannock Chase", areas: [{ coordinates: [[17, 42]] }] },
  { name: "Stone", areas: [{ coordinates: [[18, 41]] }] },
  { name: "Staffordshire Moorlands", areas: [{ coordinates: [[19, 40]] }] },
  { name: "Rother Valley", areas: [{ coordinates: [[20, 39]] }] },
  { name: "Doncaster Central", areas: [{ coordinates: [[21, 38]] }] },
  { name: "Don Valley", areas: [{ coordinates: [[22, 37]] }] },
  { name: "Brigg & Goole", areas: [{ coordinates: [[23, 36]] }] },
  { name: "Doncaster North", areas: [{ coordinates: [[24, 35]] }] },
  { name: "Haltemprice & Howden", areas: [{ coordinates: [[25, 34]] }] },
  { name: "Cleethorpes", areas: [{ coordinates: [[26, 33]] }] },
  { name: "Eddisbury", areas: [{ coordinates: [[12, 49]] }] },
  { name: "Altrincham & Sale West", areas: [{ coordinates: [[13, 48]] }] },
  { name: "Manchester Withington", areas: [{ coordinates: [[14, 47]] }] },
  { name: "Manchester Gorton", areas: [{ coordinates: [[15, 46]] }] },
  { name: "Walsall North", areas: [{ coordinates: [[16, 45]] }] },
  { name: "Aldridge-Brownhills", areas: [{ coordinates: [[17, 44]] }] },
  { name: "Stafford", areas: [{ coordinates: [[18, 43]] }] },
  { name: "Derbyshire Dales", areas: [{ coordinates: [[19, 42]] }] },
  { name: "High Peak", areas: [{ coordinates: [[20, 41]] }] },
  { name: "Derbyshire North East", areas: [{ coordinates: [[21, 40]] }] },
  { name: "Chesterfield", areas: [{ coordinates: [[22, 39]] }] },
  { name: "Bassetlaw", areas: [{ coordinates: [[23, 38]] }] },
  { name: "Scunthorpe", areas: [{ coordinates: [[24, 37]] }] },
  { name: "Hull West & Hessle", areas: [{ coordinates: [[25, 36]] }] },
  { name: "Hull North", areas: [{ coordinates: [[26, 35]] }] },
  { name: "Crewe & Nantwich", areas: [{ coordinates: [[12, 51]] }] },
  { name: "Tatton", areas: [{ coordinates: [[13, 50]] }] },
  { name: "Wythenshawe & Sale East", areas: [{ coordinates: [[14, 49]] }] },
  { name: "Stockport", areas: [{ coordinates: [[15, 48]] }] },
  { name: "Wolverhampton South East", areas: [{ coordinates: [[16, 47]] }] },
  { name: "Walsall South", areas: [{ coordinates: [[17, 46]] }] },
  { name: "Lichfield", areas: [{ coordinates: [[18, 45]] }] },
  { name: "Burton", areas: [{ coordinates: [[19, 44]] }] },
  { name: "Derbyshire Mid", areas: [{ coordinates: [[20, 43]] }] },
  { name: "Bolsover", areas: [{ coordinates: [[21, 42]] }] },
  { name: "Mansfield", areas: [{ coordinates: [[22, 41]] }] },
  { name: "Sherwood", areas: [{ coordinates: [[23, 40]] }] },
  { name: "Newark", areas: [{ coordinates: [[24, 39]] }] },
  { name: "Great Grimsby", areas: [{ coordinates: [[25, 38]] }] },
  { name: "Congleton", areas: [{ coordinates: [[13, 52]] }] },
  { name: "Macclesfield", areas: [{ coordinates: [[14, 51]] }] },
  { name: "Cheadle", areas: [{ coordinates: [[15, 50]] }] },
  { name: "Dudley North", areas: [{ coordinates: [[16, 49]] }] },
  { name: "West Bromwich East", areas: [{ coordinates: [[17, 48]] }] },
  { name: "Tamworth", areas: [{ coordinates: [[18, 47]] }] },
  { name: "Derbyshire South", areas: [{ coordinates: [[19, 46]] }] },
  { name: "Derby North", areas: [{ coordinates: [[20, 45]] }] },
  { name: "Amber Valley", areas: [{ coordinates: [[21, 44]] }] },
  { name: "Ashfield", areas: [{ coordinates: [[22, 43]] }] },
  { name: "Nottingham North", areas: [{ coordinates: [[23, 42]] }] },
  { name: "Lincoln", areas: [{ coordinates: [[24, 41]] }] },
  { name: "Gainsborough", areas: [{ coordinates: [[25, 40]] }] },
  { name: "Staffordshire South", areas: [{ coordinates: [[13, 54]] }] },
  { name: "Wolverhampton South West", areas: [{ coordinates: [[14, 53]] }] },
  { name: "Wolverhampton North East", areas: [{ coordinates: [[15, 52]] }] },
  { name: "West Bromwich West", areas: [{ coordinates: [[16, 51]] }] },
  { name: "Warley", areas: [{ coordinates: [[17, 50]] }] },
  { name: "Birmingham Erdington", areas: [{ coordinates: [[18, 49]] }] },
  { name: "Sutton Coldfield", areas: [{ coordinates: [[19, 48]] }] },
  { name: "Leicestershire North West", areas: [{ coordinates: [[20, 47]] }] },
  { name: "Derby South", areas: [{ coordinates: [[21, 46]] }] },
  { name: "Charnwood", areas: [{ coordinates: [[22, 45]] }] },
  { name: "Broxtowe", areas: [{ coordinates: [[23, 44]] }] },
  { name: "Gelding", areas: [{ coordinates: [[24, 43]] }] },
  { name: "Sleaford & North Hykeham", areas: [{ coordinates: [[25, 42]] }] },
  { name: "Louth & Horncastle", areas: [{ coordinates: [[26, 41]] }] },
  { name: "Dudley South", areas: [{ coordinates: [[13, 56]] }] },
  { name: "Halesowen & Rowley Regis", areas: [{ coordinates: [[14, 55]] }] },
  { name: "Birmingham Edgbaston", areas: [{ coordinates: [[15, 54]] }] },
  { name: "Birmingham Ladywood", areas: [{ coordinates: [[16, 53]] }] },
  { name: "Birmingham Perry Barr", areas: [{ coordinates: [[17, 52]] }] },
  { name: "Birmingham Hodge Hill", areas: [{ coordinates: [[18, 51]] }] },
  { name: "Warwickshire North", areas: [{ coordinates: [[19, 50]] }] },
  { name: "Bosworth", areas: [{ coordinates: [[20, 49]] }] },
  { name: "Leicester West", areas: [{ coordinates: [[21, 48]] }] },
  { name: "Leicester East", areas: [{ coordinates: [[22, 47]] }] },
  { name: "Erewash", areas: [{ coordinates: [[23, 46]] }] },
  { name: "Nottingham South", areas: [{ coordinates: [[24, 45]] }] },
  { name: "Nottingham East", areas: [{ coordinates: [[25, 44]] }] },
  { name: "Boston & Skegness", areas: [{ coordinates: [[26, 43]] }] },

  // WALES

  { name: "Aberavon", areas: [{ coordinates: [[8, 63]] }] },
  { name: "Aberconwy", areas: [{ coordinates: [[9, 48]] }] },
  { name: "Alyn & Deeside", areas: [{ coordinates: [[11, 52]] }] },
  { name: "Arfon", areas: [{ coordinates: [[8, 49]] }] },
  { name: "Blaenau Gwent", areas: [{ coordinates: [[10, 59]] }] },
  { name: "Brecon & Radnorshire", areas: [{ coordinates: [[12, 57]] }] },
  { name: "Bridgend", areas: [{ coordinates: [[7, 66]] }] },
  { name: "Caerphilly", areas: [{ coordinates: [[11, 64]] }] },
  { name: "Cardiff Central", areas: [{ coordinates: [[11, 66]] }] },
  { name: "Cardiff North", areas: [{ coordinates: [[10, 65]] }] },
  { name: "Cardiff South & Penarth", areas: [{ coordinates: [[12, 65]] }] },
  { name: "Cardiff West", areas: [{ coordinates: [[9, 66]] }] },
  { name: "Carmarthen East & Dinefwr", areas: [{ coordinates: [[6, 63]] }] },
  { name: "Carmarthen West & Pembrokeshire South", areas: [{ coordinates: [[6, 65]] }] },
  { name: "Ceredigion", areas: [{ coordinates: [[11, 58]] }] },
  { name: "Clwyd West", areas: [{ coordinates: [[9, 50]] }] },
  { name: "Clywd South", areas: [{ coordinates: [[12, 55]] }] },
  { name: "Cynon Valley", areas: [{ coordinates: [[11, 62]] }] },
  { name: "Delyn", areas: [{ coordinates: [[11, 50]] }] },
  { name: "Dwyfor Meirionnydd", areas: [{ coordinates: [[11, 54]] }] },
  { name: "Gower", areas: [{ coordinates: [[7, 62]] }] },
  { name: "Islwyn", areas: [{ coordinates: [[10, 61]] }] },
  { name: "Llanelli", areas: [{ coordinates: [[5, 64]] }] },
  { name: "Merthyr Tydfil & Rhymney", areas: [{ coordinates: [[9, 60]] }] },
  { name: "Monmouth", areas: [{ coordinates: [[12, 59]] }] },
  { name: "Montgomeryshire", areas: [{ coordinates: [[11, 56]] }] },
  { name: "Neath", areas: [{ coordinates: [[9, 62]] }] },
  { name: "Newport East", areas: [{ coordinates: [[12, 61]] }] },
  { name: "Newport West", areas: [{ coordinates: [[12, 63]] }] },
  { name: "Ogmore", areas: [{ coordinates: [[8, 65]] }] },
  { name: "Pontypridd", areas: [{ coordinates: [[9, 64]] }] },
  { name: "Preseli Pembrokeshire", areas: [{ coordinates: [[5, 66]] }] },
  { name: "Rhondda", areas: [{ coordinates: [[10, 63]] }] },
  { name: "Swansea East", areas: [{ coordinates: [[8, 61]] }] },
  { name: "Swansea West", areas: [{ coordinates: [[7, 64]] }] },
  { name: "Torfaen", areas: [{ coordinates: [[11, 60]] }] },
  { name: "Vale Of Clwyd", areas: [{ coordinates: [[10, 49]] }] },
  { name: "Vale Of Glamorgan", areas: [{ coordinates: [[8, 67]] }] },
  { name: "Wrexham", areas: [{ coordinates: [[12, 53]] }] },
  { name: "Ynys Mon", areas: [{ coordinates: [[7, 46]] }] },

  // LONDON
  
  { name: "Barking", areas: [{ coordinates: [[28, 63]] }] },
  { name: "Battersea", areas: [{ coordinates: [[22, 69]] }] },
  { name: "Beckenham", areas: [{ coordinates: [[26, 73]] }] },
  { name: "Bermondsey & Old Southwark", areas: [{ coordinates: [[25, 66]] }] },
  { name: "Bethnal Green & Bow", areas: [{ coordinates: [[26, 69]] }] },
  { name: "Bexleyheath & Crayford", areas: [{ coordinates: [[29, 70]] }] },
  { name: "Brent Central", areas: [{ coordinates: [[24, 63]] }] },
  { name: "Brent North", areas: [{ coordinates: [[21, 64]] }] },
  { name: "Brentford & Isleworth", areas: [{ coordinates: [[21, 70]] }] },
  { name: "Bromley & Chislehurst", areas: [{ coordinates: [[27, 72]] }] },
  { name: "Camberwell & Peckham", areas: [{ coordinates: [[25, 68]] }] },
  { name: "Carshalton & Wallington", areas: [{ coordinates: [[22, 73]] }] },
  { name: "Chelsea & Fulham", areas: [{ coordinates: [[24, 65]] }] },
  { name: "Chingford & Woodford Green", areas: [{ coordinates: [[27, 60]] }] },
  { name: "Chipping Barnet", areas: [{ coordinates: [[22, 61]] }] },
  { name: "Cities Of London & Westminster", areas: [{ coordinates: [[24, 67]] }] },
  { name: "Croydon Central", areas: [{ coordinates: [[24, 73]] }] },
  { name: "Croydon North", areas: [{ coordinates: [[25, 72]] }] },
  { name: "Croydon South", areas: [{ coordinates: [[23, 74]] }] },
  { name: "Dagenham & Rainham", areas: [{ coordinates: [[29, 66]] }] },
  { name: "Dulwich & West Norwood", areas: [{ coordinates: [[25, 70]] }] },
  { name: "Ealing Central & Acton", areas: [{ coordinates: [[21, 68]] }] },
  { name: "Ealing North", areas: [{ coordinates: [[20, 67]] }] },
  { name: "Ealing Southall", areas: [{ coordinates: [[20, 69]] }] },
  { name: "East Ham", areas: [{ coordinates: [[28, 65]] }] },
  { name: "Edmonton", areas: [{ coordinates: [[26, 61]] }] },
  { name: "Eltham", areas: [{ coordinates: [[28, 69]] }] },
  { name: "Enfield North", areas: [{ coordinates: [[24, 59]] }] },
  { name: "Enfield Southgate", areas: [{ coordinates: [[23, 60]] }] },
  { name: "Erith & Thamesmead", areas: [{ coordinates: [[29, 68]] }] },
  { name: "Feltham & Heston", areas: [{ coordinates: [[19, 70]] }] },
  { name: "Finchley & Golders Green", areas: [{ coordinates: [[22, 63]] }] },
  { name: "Greenwich & Woolwich", areas: [{ coordinates: [[28, 67]] }] },
  { name: "Hackney North & Stoke Newington", areas: [{ coordinates: [[26, 65]] }] },
  { name: "Hackney South & Shoreditch", areas: [{ coordinates: [[26, 67]] }] },
  { name: "Hammersmith", areas: [{ coordinates: [[22, 67]] }] },
  { name: "Hampstead & Kilburn", areas: [{ coordinates: [[21, 66]] }] },
  { name: "Harrow East", areas: [{ coordinates: [[20, 63]] }] },
  { name: "Harrow West", areas: [{ coordinates: [[20, 65]] }] },
  { name: "Hayes & Harlington", areas: [{ coordinates: [[19, 68]] }] },
  { name: "Hendon", areas: [{ coordinates: [[21, 62]] }] },
  { name: "Holborn & St Pancras", areas: [{ coordinates: [[23, 64]] }] },
  { name: "Hornchurch & Upminster", areas: [{ coordinates: [[29, 64]] }] },
  { name: "Hornsey & Wood Green", areas: [{ coordinates: [[23, 62]] }] },
  { name: "Ilford North", areas: [{ coordinates: [[28, 61]] }] },
  { name: "Ilford South", areas: [{ coordinates: [[27, 62]] }] },
  { name: "Islington North", areas: [{ coordinates: [[25, 62]] }] },
  { name: "Islington South & Finsbury", areas: [{ coordinates: [[25, 64]] }] },
  { name: "Kensington", areas: [{ coordinates: [[23, 68]] }] },
  { name: "Kingston & Surbiton", areas: [{ coordinates: [[20, 73]] }] },
  { name: "Lewisham Deptford", areas: [{ coordinates: [[27, 68]] }] },
  { name: "Lewisham East", areas: [{ coordinates: [[27, 70]] }] },
  { name: "Lewisham West & Penge", areas: [{ coordinates: [[26, 71]] }] },
  { name: "Leyton & Wanstead", areas: [{ coordinates: [[26, 63]] }] },
  { name: "Mitcham & Morden", areas: [{ coordinates: [[23, 72]] }] },
  { name: "Old Bexley & Sidcup", areas: [{ coordinates: [[28, 71]] }] },
  { name: "Orpington", areas: [{ coordinates: [[25, 74]] }] },
  { name: "Poplar & Limehouse", areas: [{ coordinates: [[27, 66]] }] },
  { name: "Putney", areas: [{ coordinates: [[23, 66]] }] },
  { name: "Richmond Park", areas: [{ coordinates: [[21, 72]] }] },
  { name: "Romford", areas: [{ coordinates: [[29, 62]] }] },
  { name: "Ruislip, Northwood & Pinner", areas: [{ coordinates: [[19, 64]] }] },
  { name: "Streatham", areas: [{ coordinates: [[23, 70]] }] },
  { name: "Sutton & Cheam", areas: [{ coordinates: [[21, 74]] }] },
  { name: "Tooting", areas: [{ coordinates: [[22, 71]] }] },
  { name: "Tottenham", areas: [{ coordinates: [[24, 61]] }] },
  { name: "Twickenham", areas: [{ coordinates: [[20, 71]] }] },
  { name: "Uxbridge & South Ruislip", areas: [{ coordinates: [[19, 66]] }] },
  { name: "Vauxhall", areas: [{ coordinates: [[24, 69]] }] },
  { name: "Walthamstow", areas: [{ coordinates: [[25, 60]] }] },
  { name: "West Ham", areas: [{ coordinates: [[27, 64]] }] },
  { name: "Westminster North", areas: [{ coordinates: [[22, 65]] }] },
  { name: "Wimbledon", areas: [{ coordinates: [[24, 71]] }] }

];
